#creating an ec2 instance
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref pemkey
      DisableApiTermination: false 
      ImageId: !Ref amiid
      InstanceType: !Ref InstanceType
      Monitoring: false
      SubnetId: !Ref pubsubnet1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo -i 
          yum update -y
          yum install -y httpd
          # Install the files and packages from the metadata
          systemctl start httpd
          systemctl enable httpd
          touch /var/www/html/index.html
          echo '<h1>successfully launched an httpd through cft  </h1>'>/var/www/html/index.html
          service httpd restart 

      SecurityGroupIds: 
          - Ref: SimpleInstanceSg
  SimpleInstanceSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref myVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
