AWSTemplateFormatVersion: '2010-09-09'
Description: 'creating VPC'
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Dev
          Value: sneha-vpc


