AWSTemplateFormatVersion: 2010-09-09
Description: template for ec2
Parameters:
  KeyPair:
    Description: key name
    Type: String
    Default: "elastic beanstalk"
Resources:
  ec2:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: us-west-2a
      ImageId: ami-08d489468314a58df
      InstanceType: t2.micro
      SecurityGroupIds: 
        - sg-07f21a31af608a6db
      KeyName: !Ref KeyPair
      Tags:
      -
        Key: Name
        Value: cf_ec2
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: cf_vpc
    
     