AWSTemplateFormatVersion: 2010-09-09
Description: writing template on vpc
Metadata:
  Authors:
    Description: IBEXlabs
Parameters:
  vpccidr:
    Description: enter cidr block range
    Type: String
  vpcsubnets:
    Description: enter cidr block range
    Type: CommaDelimitedList
    Default: "10.3.1.0/24, 10.3.2.0/24, 10.3.3.0/24, 10.3.4.0/24"
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref vpccidr
      EnableDnsSupport: true
      Tags:
        - Key: name
          Value: tishi
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: name
          Value: sneha
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref InternetGateway
  subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref myVPC
      CidrBlock: !Select [ 0, !Ref vpcsubnets ]
      Tags:
        - Key: name
          Value: sneha
  subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref myVPC
      CidrBlock: !Select [ 1, !Ref vpcsubnets ]
      Tags:
       - Key: name
         Value: sneha
  subnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      VpcId: !Ref myVPC
      CidrBlock: !Select [ 2, !Ref vpcsubnets ]
      Tags:
        - Key: name
          Value: sneha
  subnet4:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref myVPC
      CidrBlock: !Select [ 3, !Ref vpcsubnets ]
      Tags:
        - Key: name
          Value: sneha
  eipName:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  natName:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt eipName.AllocationId
      SubnetId: !Ref subnet1
  
