myVPC:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: 10.0.0.0/16
    EnableDnsSupport: true
    Tags:
      - Key: keyname
        Value: value
subnetName:
  Type: AWS::EC2::Subnet
  Properties:
    AvailabilityZone: zone-id
    VpcId: vpc-id
    CidrBlock: --.--.--.--/--
    Tags:
      - Key: keyname
        Value: value        
LogicalID:
  Type: "AWS::EC2::NatGateway"
  Properties:
    AllocationId: String #required
    SubnetId: String #required
    Tags:
      - Tag
igwName:
  Type: AWS::EC2::InternetGateway
  Properties:
    Tags:
      - Key: keyname
        Value: value
AttachGateway:
  Type: AWS::EC2::VPCGatewayAttachment
  Properties:
    VpcId: !Ref myVPC
    InternetGatewayId: !Ref igwName      
