AWSTemplateFormatVersion: 2010-09-09
Description: A simple WordPress website using CFT with user data
#Metadata: 

#Parameters:
 



#Mappings: 
#Conditions: 

Resources: 
 

  myInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: virginia
      DisableApiTermination: false
      ImageId: ami-00eb20669e0990cb4
      InstanceType: t2.micro
      Monitoring: false
      SecurityGroupIds: 
        - sg-018552a77fb732e64
      Tags:
        - Key: Name
          Value: WordPress
      UserData:
        Fn::Base64: 
          !Sub |
          #!/bin/bash
          sudo su -
          yum install httpd -y
          service httpd start
          yum install php php-mysql -y
          service httpd restart
          cd /var/www/html
          echo "<?php phpinfo() ?>" >> test.php
          yum install mysql-server -y
          service mysqld start
          mysqladmin -u root create mydb
          mysqladmin --user=root password "ana"
          cd /var/www/html
          wget https://wordpress.org/wordpress-5.1.1.tar.gz
          tar -xvf wordpress-5.1.1.tar.gz
          cd wordpress
          mv wp-config-sample.php wp-config.php
          ex -s -c '%s/database_name_here/mydb/g|x' wp-config.php
          ex -s -c '%s/localhost/localhost/g|x' wp-config.php
          ex -s -c '%s/username_here/root/g|x' wp-config.php
          ex -s -c '%s/password_here/ana/g|x' wp-config.php
          mv /var/www/html/wordpress/* /var/www/html



#Outputs: